diverssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import wiki, users

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("", include("public.urls")),
    path("polls/", include("polls.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls'), name = "accounts"),
    path("users/", include("users.urls")),
    path("wiki/", include("wiki.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("mail/", include("mail.urls")),
    # these protect private media files
    path("media/private/wiki/<str:file>", wiki.views.secure, name="secure"),
    path("media/private/profile/<str:user>/<str:file>", users.views.secure, name="secure"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path("", views.IndexView.as_view(), name="index"),
    path("<slug:slug>/", views.IndexView.as_view(), name="categ"),
    # path('<int:event_id>/', views.detail, name='detail'),
]

mail/urls.py
from django.urls import path

from . import views

app_name = "mail"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("compose/", views.ComposeView.as_view(), name="compose"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

from users.views import AccountActivateView, Login, ProfileView, RegComplete, SignUpView

app_name = "users"


urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_mail.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html", success_url=reverse_lazy("users:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("signup/", SignUpView.as_view(template_name="users/signup.html"), name="signup"),
    # path('activate/', AccountActivateView.as_view(template_name='account_activation.html'), name = 'activate'),
    path("thanks/", RegComplete.as_view(), name="thanks"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path(
        "change-password/",
        views.PasswordChangeView.as_view(success_url=reverse_lazy("users:password_change_done")),
        name="change_password",
    ),
    path(
        "password_change_done/",
        views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
]

wiki/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views

app_name = "wiki"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<slug:slug>/", views.DetailView.as_view(), name="detail"),
]

templates/page/base_generic.html
<!DOCTYPE html>
<html lang="en" class="h-100">
  {% load static %}
  <head>

    {% include "page/head.html" %}
  </head>
    <body class="d-flex flex-column h-100">
    <!-- add navigation bar -->
    {% comment %} <div class="container pb-0"> {% endcomment %}
        <nav class="site-header sticky-top py-1 bg-white p-0 m-0">
            {% comment %} <div class="container d-flex flex-column flex-md-row justify-content-between"> {% endcomment %}
            {% include "page/page_head.html" %}
            <hr class="m-0">
            {% include "page/nav.html" %}
        </nav>
    {% comment %} </div> {% endcomment %}
    <main role="main" class="pt-0 bg-light">

      <!-- dynamic content -->
      {% block content %}
      {% endblock %}



    </main>


    <!-- add scripts and footer part of website -->
    {% include "page/footer.html" %}
    {% include "page/scripts.html" %}
  </body>
</html>

templates/page/footer.html
<!-- <footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">© Florian Schunck 2020</span>
  </div>
</footer> -->
<script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<script language="JavaScript">
    function toggle(source) {
        checkboxes = document.getElementsByName('recipients');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>

templates/page/head.html
{% load static %}
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Ultimate Frisbee Team Leipzig Saxy Divers">
<meta name="author" content="Florian Schunck">
<meta name="google-site-verification" content="Ir1LNwXbT4AFEp0JhzPB6ykUpidYAiLIyxHGSQqsyM8" />
<title>Divers Ultimate Leipzig</title>


<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- Custom styles for this template -->
<link type="text/css" href="{% static '/css/sticky-footer-navbar.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="https://cdn.jsdelivr.net/npm/tag-it@2.0.0/css/jquery.tagit.css" rel="stylesheet" type="text/css">

<!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<!-- <link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png"> -->
<link rel="icon" href="/static/images/icon.png" type="image/png">
<!-- <link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png"> -->
<!-- <link rel="manifest" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json"> -->
<!-- <link rel="mask-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c"> -->
<!-- <link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon.ico"> -->
<!-- <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml"> -->
<meta name="theme-color" content="#563d7c">


<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }
  .wrapper {
      display: flex;
      width: 100%;
      align-items: stretch;
  }
  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  body {
    /* min-height: 100vh; */
    display: flex;
    flex-direction: column;
    /* padding-top: 3rem; */
  }

  .carousel {
      background-color: "black";


  }


</style>

templates/page/nav.html
{% load static %}
<div class="row pl-3 pr-3 pt-1 pb-1 m-0 justify-content-between">
    <a class="nav-link text-muted" href="{% url 'public:index'%}">Home</a>
    <a class="nav-link text-muted" href="{% url 'events:index' %}">Events</a>
    <a class="nav-link text-muted" href="{% url 'wiki:index' %}">Wiki</a>
    {% comment %} <a class="nav-link text-muted" href="#">Fotos</a>
    <a class="nav-link text-muted" href="#">Novembernebel</a> {% endcomment %}
    <a class="nav-link text-muted" href="#">Fotos</a>
    <a class="nav-link text-muted" href="#">Novembernebel</a>
</div>

templates/page/page_head.html
<div class="row flex justify-content-between align-items-center pl-3 pr-3 pt-2 pb-2 m-0">
  <div class="col-6 text-left">
    <a class="lead text-dark" href="{% url 'public:index' %}">Divers Ultimate</a>
  </div>
  <div class="col-6 d-flex justify-content-end align-items-center">

    {% if user.is_staff %}
    <a href="{% url 'admin:index' %}" class="btn btn-sm btn-outline-secondary">settings</a>
    &nbsp;
    <a class="btn btn-sm btn-outline-secondary" data-toggle="collapse" href="#collapseProfile" aria-expanded="false">{{user.username}}</a>
    {% elif user.is_authenticated%}
    <a class="btn btn-sm btn-outline-secondary" data-toggle="collapse" href="#collapseProfile" aria-expanded="false">{{user.username}}</a>
    {% else %}
    <a href="{% url 'users:login' %}?next={{request.path}}" class="btn btn-sm btn-outline-secondary"> log in</a>
    &nbsp;
    &nbsp;
    <a href="{% url 'users:signup' %}?next={{request.path}}" class="btn btn-sm btn-outline-secondary"> sign up</a>
    {% endif %}
  </div>
</div>
<div class="collapse" id="collapseProfile">
  <div class="row flex pt-0 pb-2 pr-3">
    <div class="col-4"> </div>
    <div class="col-8 text-right">
      {% if user.is_authenticated %}
      <a class="text-muted" href="{% url 'users:profile' %}">Profile</a>&nbsp;|
      <a class="text-muted" href="{% url 'mail:index'%}">Mailbox</a>&nbsp;|
      <a class="text-muted" href="{% url 'users:logout' %}?next={% url 'public:index' %}">logout</a>
      {% endif %}
    </div>
  </div>
</div>  

templates/page/scripts.html
{% load static %}
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
<!-- imported as a submodule-->
<script type="application/javascript" src="https://cdn.jsdelivr.net/npm/tag-it@2.0.0/js/tag-it.min.js" charset="utf-8"></script>
<script>
  var search_data = JSON.parse("{{search_data|escapejs}}"); 
  $( function() {
    $( "#search_keys" ).autocomplete({
      source: search_data
    });
  } );
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var search_data = JSON.parse("{{search_data|escapejs}}"); 

        $("#tag_keys").tagit({
            availableTags: search_data,
            removeConfirmation: true,
            allowSpaces: true,
            fieldName: 'recipients'
        });
    });
</script>