diverssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import wiki, users

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("", include("public.urls")),
    path("polls/", include("polls.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls'), name = "accounts"),
    path("users/", include("users.urls")),
    path("wiki/", include("wiki.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("mail/", include("mail.urls")),
    # these protect private media files
    path("media/private/wiki/<str:file>", wiki.views.secure, name="secure"),
    path("media/private/profile/<str:user>/<str:file>", users.views.secure, name="secure"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

app_name = "mail"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("compose/", views.ComposeView.as_view(), name="compose"),
]

wiki/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views

app_name = "wiki"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<slug:slug>/", views.DetailView.as_view(), name="detail"),
]

wiki/models.py
import os
import io
import PIL
from PIL import ImageOps
from django.core.files import File
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from simple_history.models import HistoricalRecords

# Create your models here.
from events.models import Event


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Display(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


vis_choice = (("public", "Public"), ("members", "Members"))


def file_directory_path(instance, filename, check_similar=True):
    try:
        event = instance.event.name
        date = instance.event.date.strftime("%Y%m%d")
    except AttributeError:
        event = ""
        date = instance.date.strftime("%Y%m%d")

    title = "unnamed" if instance.title == "" else instance.title
    public = "public" if instance.public else "private"

    slug = slugify("-".join([type(instance).__name__, event, date, title]))

    if check_similar:
        similar_files = [i.file.name for i in Image.objects.all() if slug in i.file.name]
        slug = slug + "-" + str(len(similar_files))

    ext = filename.split(".")[-1]
    return f"{public}/wiki/{slug}.{ext}"


def file_directory_path_tumbnail(instance, filename):
    path = file_directory_path(instance, filename, check_similar=False)
    head, ext = os.path.splitext(path)
    return f"{head}-thumb{ext}"


# https://stackoverflow.com/questions/34006994/how-to-upload-multiple-images-to-a-blog-post-in-django/34007383
# hier gehts weiter
class Image(models.Model):
    title = models.CharField(max_length=20, default=None, blank=True)
    event = models.ForeignKey(Event, blank=True, null=True, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    file = models.ImageField(upload_to=file_directory_path, verbose_name="Image")
    thumbnail = models.ImageField(
        upload_to=file_directory_path_tumbnail, default="/static/images/default_profile_thumbnail.png", editable=False
    )
    public = models.BooleanField(default=False)
    # history = HistoricalRecords()

    def __str__(self):
        return os.path.basename(self.file.path)

    def image_url(self):
        """
        Returns the URL of the image associated with this Object.
        If an image hasn't been uploaded yet, it returns a stock image

        :returns: str -- the image url

        """
        default = "/static/images/default_profile.png"
        if self.file and hasattr(self.file, "url"):
            if default in self.file.url:
                return default
            return self.file.url
        else:
            return default

    def thumb_url(self):
        """
        Returns the URL of the image associated with this Object.
        If an image hasn't been uploaded yet, it returns a stock image

        :returns: str -- the image url

        """
        default = "/static/images/default_profile_thumbnail.png"

        if self.thumbnail and hasattr(self.thumbnail, "url"):
            if default in self.thumbnail.url:
                return default
            return self.thumbnail.url
        else:
            return default

    def save(self, *args, **kwargs):
        if not self.file:
            self.thumbnail = None
        else:
            # extract path from old file and append thumbnail
            thumb_path = file_directory_path_tumbnail(self, os.path.basename(self.file.path))

            # create byte buffer
            buf = io.BytesIO()

            # open original image, transpose to address exif tags,
            # resize and save to buffer
            thumbnail_size = 100, 100
            tiny_img = PIL.Image.open(self.file)
            tiny_img = ImageOps.exif_transpose(tiny_img)
            tiny_img.thumbnail(thumbnail_size)
            tiny_img.save(buf, format="JPEG")

            # save new objects to thumbnail field
            self.thumbnail.file = File(buf)
            self.thumbnail.name = thumb_path

            # save image to media with thumbnail path property
            tiny_img.save(self.thumbnail.path, format="JPEG")

        super(Image, self).save(*args, **kwargs)


class File(models.Model):
    title = models.CharField(max_length=20, default=None, blank=True)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    file = models.FileField(upload_to=file_directory_path, verbose_name="File")
    public = models.BooleanField(default=False)

    # history = HistoricalRecords()

    def __str__(self):
        return os.path.basename(self.file.path)

    def file_url(self):
        if self.file and hasattr(self.file, "url"):
            return self.file.url
        else:
            raise FileNotFoundError

    def file_type_icon(self):
        if self.file and hasattr(self.file, "url"):
            url = self.file.url
            if ".xlsx" in url or ".xls" in url:
                return "/static/images/excel.png"

            if ".docx" in url or ".doc" in url:
                return "/static/images/word.png"

            if ".pdf" in url:
                return "/static/images/pdf.png"

            else:
                return "/static/images/document.png"

        else:
            raise FileNotFoundError


class Article(models.Model):
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=200)
    text = MarkdownxField()
    pub_date = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=50)
    visibility = models.CharField(max_length=20, default="public", choices=vis_choice)
    show_on_pages = models.ManyToManyField(Display)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True)
    history = HistoricalRecords()
    files = models.ManyToManyField(File, default=None, blank=True)
    images = models.ManyToManyField(Image, default=None, blank=True)

    # Create your models here.

    # Create a property that returns the markdown instead
    @property
    def formatted_markdown(self):
        return markdownify(self.text)

    def __str__(self):
        return self.title

wiki/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple


class ArticleAdminForm(forms.ModelForm):
    class Meta:
        widgets = {
            "category": CheckboxSelectMultiple,
            "show_on_pages": CheckboxSelectMultiple,
        }

wiki/views.py
import os
from django.http.response import FileResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import View, generic
from django.contrib.auth.decorators import login_required

from .models import Article, Category, Image, File
from . import models


def get_articles_for_user(user):
    if user.is_active:
        return Article.objects.all()
    else:
        return Article.objects.filter(visibility="public")


def nest_articles_in_categories(articles):
    categories = Category.objects.all()
    category_system = dict()
    for cat in categories:
        category_system[cat] = articles.filter(category=cat)

    return category_system


class IndexView(View):
    template_name = "wiki/index.html"

    def get(self, request):
        articles = get_articles_for_user(user=request.user)
        category_system = nest_articles_in_categories(articles=articles)

        articles_query = articles.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

        context = {
            "articles": articles_query,
            "categories": category_system,
        }

        return render(request, self.template_name, context)


@login_required
def secure(request, file):
    if "image" in file:
        model = Image
    elif "file" in file:
        model = File
    else:
        raise NotImplementedError

    file = get_object_or_404(model, file=f"private/wiki/{file}")
    response = FileResponse(file.file)
    return response


class DetailView(UserPassesTestMixin, generic.DetailView):
    model = Article
    login_url = "/users/login/"
    template_name = "wiki/detail.html"

    def test_func(self):
        """
        test function for class UserPassesTestMixin to regulate access to
        article
        """
        u = self.request.user
        a = Article.objects.get(slug=self.kwargs["slug"])
        if u.is_active:
            return True
        elif a.visibility == "public":
            return True
        else:
            return False

    def get(self, request, slug):
        articles = get_articles_for_user(user=request.user)
        category_system = nest_articles_in_categories(articles=articles)

        article = Article.objects.get(slug=slug)

        context = {
            "categories": category_system,
            "article": article,
        }

        return render(request, self.template_name, context)

wiki/templates/wiki/detail.html
{% extends "page/base_generic.html" %}
{% block content %}




<div class="container pt-3">
  <div class="row">

    <aside class="col-md-4 mt-0 bg-light">

      {% include "wiki/sidebar.html" %}
    </aside>

    <div class="col-md-8">
      <h2 >{{article.title}}</h2>
      <p>{{article.formatted_markdown|safe}}</p>
      
      <div class="row m-0">
        {% for img in article.images.all %}
        {% if img.public or user.is_authenticated %}
        <a href="{{ img.image_url }}">
            <div class="col m-0 p-0">
                <img src="{{ img.thumb_url }}"
                    class="img m-0 p-0"
                    alt= "{{ img.thumb_url }}" 
                    style="object-fit:cover;
                            width:100px;
                            height:100px;
                            border: solid 1px #CCC"/>
            </div>
        </a>
        {%endif%}
        {% endfor %}
      </div>
      {% if article.files.count > 0 %}
      <hr>
      <h4>Files</h4>
      <div class="row m-0 mt-2">
        {% for file in article.files.all %}
        {% if file.public or user.is_authenticated %}
        <a class="pr-2 pl-2" href="{{ file.file_url }}">
            <div class="col m-0 p-0">
                <img src="{{ file.file_type_icon }}"
                    class="img m-0 p-0"
                    style="object-fit:cover;
                            width:64px;
                            height:64px" />
            </div>
            <small>{{ file.title }}</small>
        </a>
        {%endif%}
        {% endfor %}
      </div>
      {% endif %}
      <br>
      <div class="row">
        {% if user.is_staff %}
        <a class="btn btn-light" role="button" href="{% url 'admin:wiki_article_change' article.id %}?next={{request.path}}">
            edit article
        </a>
        {% endif %}
      </div>


    </div>

  </div>
</div>
{% endblock %}

wiki/templates/wiki/index.html
{% extends "page/base_generic.html" %}
{% block content %}



<div class="pt-3 m-0">
  <div class="row m-0">

    <aside class="col-md-4 mt-0 pl-3 bg-light">

      {% include "wiki/sidebar.html" %}
    </aside>


    <div class="col-md-8 bg-light">
      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <h3 class="pl-0 mb-4">Latest wiki entries</h3>
          {% for art in articles %}
          <div class="container p-0 mr-2">
            <div class="card mb-3 shadow-sm">
              <div class="card-body">
                <a href="{% url 'wiki:detail' art.slug %}">{{ art.title }}</a>
                <p>{{ art.formatted_markdown|safe }}</p>

              </div>

            </div>
          </div>
          {% endfor %}
        </div>
      </div> <!-- /container -->
    </div>
  </div>
</div>
{% endblock %}

wiki/templates/wiki/sidebar.html
    <div class="">
      <h3 class="sidebar-heading mt-0">
        Wiki
      </h3>
      {% load admin_urls %}
      {% if user.is_staff %}

      <h6 class="sidebar-heading d-flex justify-content-between text-muted mt-4">
        add a wiki page
        <a class="d-flex align-items-center text-muted" href="{% url 'admin:wiki_article_add' %}?next={{request.path}}" aria-label="add a wiki page">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
        </a>
      </h6>
      {% endif %}

    </div>

    <ul class="list-unstyled components mt-4">
      {% for cat, articles in categories.items %}
      <li class="active">
        <a href="#{{cat.name}}" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          {{cat}}
        </a>
        <ul class="collapse list-unstyled show" id="{{cat.name}}">
          {% for art in articles %}
          <li class="ml-2">
            <a class="text-muted" href="{%  url 'wiki:detail' art.slug%}">
              {{art.title}}
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </ul>
</aside>

wiki/templates/wiki/sidebar_old.html
<nav>
  <div class="sidebar-sticky">
    <div class="accordion" id="wikisidebar">
      <div class="card">
        {% for cat, articles in categories.items %}
        <div class="card-header" id="{{cat.name}}_heading">
          <h2 class="mb-0">
            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#{{cat.name}}" aria-expanded="true" aria-controls="{{cat.name}}">
              {{cat}}
            </button>
          </h2>
        </div>

        <div id="{{cat.name}}" class="collapse show" aria-labelledby="headingOne" data-parent="#wikisidebar">
          {% for art in articles %}
          <div class="card-body" href="{%  url 'wiki:detail' article.id%}">
              {{art.title}}
          </div>
          {% endfor %}
        </div>

            <div class="collapse" aria-labelledby="{{cat.name}}_dropdown">
              <a class="dropdown-item" href="#">{{art.title}}</a>
            </div>

        {% endfor %}
      </div>
    </div>
  </div>
</nav>