diverssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import wiki, users

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("", include("public.urls")),
    path("polls/", include("polls.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls'), name = "accounts"),
    path("users/", include("users.urls")),
    path("wiki/", include("wiki.urls")),
    path("markdownx/", include("markdownx.urls")),
    path("mail/", include("mail.urls")),
    # these protect private media files
    path("media/private/wiki/<str:file>", wiki.views.secure, name="secure"),
    path("media/private/profile/<str:user>/<str:file>", users.views.secure, name="secure"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

app_name = "mail"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("compose/", views.ComposeView.as_view(), name="compose"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

from users.views import AccountActivateView, Login, ProfileView, RegComplete, SignUpView

app_name = "users"


urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_mail.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html", success_url=reverse_lazy("users:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("signup/", SignUpView.as_view(template_name="users/signup.html"), name="signup"),
    # path('activate/', AccountActivateView.as_view(template_name='account_activation.html'), name = 'activate'),
    path("thanks/", RegComplete.as_view(), name="thanks"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path(
        "change-password/",
        views.PasswordChangeView.as_view(success_url=reverse_lazy("users:password_change_done")),
        name="change_password",
    ),
    path(
        "password_change_done/",
        views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
]

users/models.py
import io
import os
import PIL
from PIL import ImageOps
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.files import File


# Create your models here.
def user_profile_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "profile/user_{0}/{1}".format(instance.user.id, filename)


def file_directory_path_tumbnail(instance, filename):
    path = user_profile_directory_path(instance, filename)
    head, ext = os.path.splitext(path)
    return f"{head}-thumb{ext}"


class Settings(models.Model):
    registration_password = models.CharField(max_length=20, help_text="Passwort wird bei der Registrierung abgefragt")

    def __str__(self):
        return "User Settings"

    def save(self, *args, **kwargs):
        if not self.pk and Settings.objects.exists():
            # if you'll not check for self.pk
            # then error will also raised in update of exists model
            raise ValidationError("Nur bestehender Eintrag kann geändert werden")
        return super(Settings, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional information not contained in base user
    gender = models.CharField(
        choices=(("d", "divers"), ("f", "female"), ("m", "male")), max_length=10, null=True, blank=True
    )
    trikotnummer = models.CharField(max_length=3, null=True, unique=True, blank=True)
    mobile = models.CharField(max_length=20, null=True, blank=True)
    street = models.CharField(max_length=50, null=True, blank=True)
    place = models.CharField(max_length=50, null=True, blank=True)
    zip = models.CharField(max_length=50, null=True, blank=True)
    picture = models.ImageField(upload_to=user_profile_directory_path, null=True, blank=True)
    thumbnail = models.ImageField(
        upload_to=file_directory_path_tumbnail,
        default="/static/images/default_profile_thumbnail.png",  #
        editable=False,
    )

    def image_url(self):
        """
        Returns the URL of the image associated with this Object.
        If an image hasn't been uploaded yet, it returns a stock image

        :returns: str -- the image url

        """
        default = "/static/images/default_profile.png"
        if self.picture and hasattr(self.picture, "url"):
            if default in self.picture.url:
                return default
            return self.picture.url
        else:
            return default

    def thumb_url(self):
        """
        Returns the URL of the image associated with this Object.
        If an image hasn't been uploaded yet, it returns a stock image

        :returns: str -- the image url

        """
        default = "/static/images/default_profile_thumbnail.png"

        if self.thumbnail and hasattr(self.thumbnail, "url"):
            if default in self.thumbnail.url:
                return default
            return self.thumbnail.url
        else:
            return default

    def save(self, *args, **kwargs):
        if not self.picture:
            self.thumbnail = None
        else:
            # extract path from old file and append thumbnail
            thumb_path = file_directory_path_tumbnail(self, os.path.basename(self.picture.path))

            # create byte buffer
            buf = io.BytesIO()

            # open original image, transpose to address exif tags,
            # resize and save to buffer
            thumbnail_size = 100, 100
            tiny_img = PIL.Image.open(self.picture)
            tiny_img = ImageOps.exif_transpose(tiny_img)
            tiny_img.thumbnail(thumbnail_size)
            tiny_img.save(buf, format="JPEG")

            # save new objects to thumbnail field
            self.thumbnail.file = File(buf)
            self.thumbnail.name = thumb_path

            # save image to media with thumbnail path property
            tiny_img.save(self.thumbnail.path, format="JPEG")

        super(Profile, self).save(*args, **kwargs)

    # def __str__(self):
    #     return self.user.name

users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Fieldset, Layout
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


# Sign Up Form
class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional", label="First Name")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional", label="Last Name")
    email = forms.EmailField(max_length=254, label="E-Mail", help_text="Enter a valid email address")

    validator = forms.CharField(
        required=True,
        help_text="Dieses Passwort kannst du dir im Training oder bei anderen Mitgliedern erfragen",
        label="Secret Code",
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UpdateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Fieldset(
                "Personal Info:",
                Div(Div("first_name", css_class="col-sm"), Div("last_name", css_class="col-sm"), css_class="row"),
                Div(Div("email", css_class="col-sm"), css_class="row"),
            )
        )

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
        ]


class ProfileForm(forms.ModelForm):

    trikotnummer = forms.CharField(
        required=True, error_messages={"unique": "Occupied :-( Check the wiki to see which numbers are still free"}
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.error_text_inline = False
        self.helper.layout = Layout(
            Fieldset(
                "Divers Info:",
                Div(Div("gender", css_class="col-sm"), Div("trikotnummer", css_class="col-sm"), css_class="row"),
            )
        )

    class Meta:
        model = Profile
        fields = ["gender", "trikotnummer"]


class AddressForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.error_text_inline = False
        self.helper.layout = Layout(
            Fieldset(
                "Connect:",
                Div(
                    Div("street", css_class="col-sm"),
                    Div("place", css_class="col-sm"),
                    Div("zip", css_class="col-sm"),
                    Div("mobile", css_class="col-sm"),
                    css_class="row",
                ),
            )
        )

    class Meta:
        model = Profile
        fields = [
            "street",
            "place",
            "zip",
            "mobile",
        ]


class ProfilePictureForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.disable_csrf = True

    class Meta:
        model = Profile
        fields = [
            "picture",
        ]

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.http.response import FileResponse
from django.shortcuts import render, reverse, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import AddressForm, ProfileForm, ProfilePictureForm, SignupForm, UpdateUserForm
from .models import Profile, Settings


class Login(LoginView):
    template_name = "users/login.html"


class AccountActivateView:
    pass


class SignUpView(generic.View):
    template_name = "users/signup.html"

    def post(self, request):
        signup_form = SignupForm(request.POST, request.FILES)

        if (
            signup_form.is_valid()
            and signup_form.cleaned_data["validator"]
            == Settings.objects.values("registration_password")[0]["registration_password"]
        ):
            user = signup_form.save(commit=False)
            user.save()
            return HttpResponseRedirect(reverse("users:thanks"))

        else:
            print(
                signup_form.cleaned_data["validator"],
                Settings.objects.values("registration_password")[0]["registration_password"],
            )
            error = "please make sure your information are correct."
            context = {
                "signup_form": signup_form,
                "error": error,
            }
            return render(request, self.template_name, context)

    def get(self, request):
        signup_form = SignupForm()
        context = {
            "signup_form": signup_form,
        }
        return render(request, self.template_name, context)


class RegComplete(generic.View):
    template_name = "users/thanks.html"

    def get(self, request):
        return render(request, self.template_name)


class ProfileView(LoginRequiredMixin, generic.DetailView):
    # print(selrequest)
    model = User
    login_url = "/users/login/"
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/profile.html"
    redirect_field_name = "next"

    # def test_func(self, request, username):
    #     return self.request.user.username == username

    def setup_forms(self, u):
        try:
            self.profile = Profile.objects.get(user=u)
        except:
            self.profile = Profile.objects.create(user=u)

        self.updateuser_form = UpdateUserForm(instance=u, prefix="user")
        self.updateprofile_form = ProfileForm(instance=self.profile, prefix="profile")
        self.updateaddress_form = AddressForm(instance=self.profile, prefix="address")
        self.profilepicture_form = ProfilePictureForm(instance=self.profile, prefix="pic")

    def get(self, request):

        self.setup_forms(request.user)

        context = {
            "updateuser_form": self.updateuser_form,
            "updateprofile_form": self.updateprofile_form,
            "updateaddress_form": self.updateaddress_form,
            "profilepicture_form": self.profilepicture_form,
            "profile": self.profile,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        self.setup_forms(request.user)
        userform = UpdateUserForm(request.POST, request.FILES, instance=request.user, prefix="user")
        profileform = ProfileForm(request.POST, request.FILES, instance=self.profile, prefix="profile")
        addressform = AddressForm(request.POST, request.FILES, instance=self.profile, prefix="address")
        profilepictureform = ProfilePictureForm(request.POST, request.FILES, instance=self.profile, prefix="pic")
        print(profilepictureform)

        if userform.is_valid() and profileform.is_valid() and addressform.is_valid() and profilepictureform.is_valid():
            user = userform.save(commit=False)
            user.save()
            profile = profileform.save(commit=False)
            profile.save()
            address = addressform.save(commit=False)
            address.save()
            picture = profilepictureform.save(commit=False)
            picture.save()
            return HttpResponseRedirect(reverse("users:profile"))
        else:
            context = {
                "updateuser_form": userform,
                "updateprofile_form": profileform,
                "profilepicture_form": profilepictureform,
                "updateaddress_form": addressform,
                "profile": self.profile,
            }
            return render(request, self.template_name, context)


@login_required
def secure(request, user, file):
    user_id = user.split("_")[1]
    profile = get_object_or_404(Profile, user=user_id)
    response = FileResponse(profile.picture)
    return response

users/templates/users/account_activation.html
{% extends "page/base_generic.html" %}

{% block content %}

account activation worked. You can now log in

{% endblock %}

users/templates/users/login.html
{% extends "page/base_generic.html" %}

{% block content %}
<div class="containter">

  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
      {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
      {% else %}
      <p>Please login to see this page.</p>
      {% endif %}
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}


  <table>
  <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
  </tr>
  <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
  </tr>
  </table>

  <input type="submit" value="login">
  <input type="hidden" name="next" value="{{ next }}">
  </form>

  {# Assumes you setup the password_reset view in your URLconf #}
  <p><a href="{% url 'users:password_reset' %}">Lost password?</a></p>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "page/base_generic.html" %}

{% block content %}
  <p>Logged out!</p>
  <a href="{% url 'users:login'%}">Click here to login again.</a>
{% endblock %}

users/templates/users/mail_account_activation.html
{% autoescape off %}
<h3>
    Hi {{ user.get_username }},
</h3>

To activate your account on {{ domain }},
click the link below:
<br><br>
<a href="{{ protocol }}://{{ domain }}{% url 'reset' uidb64=uid token=token %}">Reset password</a>
<br><br>
If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

users/templates/users/mail_password_reset.html
{% autoescape off %}
<h3>
    Hi {{ user.get_username }},
</h3>

To initiate the password reset process for your account on {{ domain }},
click the link below:
<br><br>
<a href="{{ protocol }}://{{ domain }}{% url 'reset' uidb64=uid token=token %}">Reset password</a>
<br><br>
If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

users/templates/users/password_change_done.html
{% extends "page/base_generic.html" %}

{% block content %}
  <p>
    password changed successfully.
  </p>
{% endblock %}

users/templates/users/password_reset.html
{% extends "page/base_generic.html" %}

{% block content %}

<h1>Forgot your password?</h1>
<p>Enter your email address below, and we'll email instructions for setting a new one.</p>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "page/base_generic.html" %}

{% block content %}
<h1>Password reset complete</h1>
<p>Your new password has been set. You can log in now on the <a href="{% url 'users:login' %}">log in page</a>.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "page/base_generic.html" %}

{% block content %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  
Please request a new password reset.</p>

{% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "page/base_generic.html" %}


{% block content %}
  <h1>Email Sent. Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}
Hi {{ user.get_username }},

To initiate the password reset process for your account on {{ domain }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Cheers.
{% endautoescape %}

users/templates/users/profile.html
{% extends "page/base_generic.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="containter p-3">
  <h2>{{user.username}}</h2>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">

      <div class="col-sm-8">
        {% crispy updateuser_form %}
        <div class="mt-2">
          <a href="{% url 'users:change_password' %}">change password</a>
        </div>
        <hr>
        {% crispy updateaddress_form %}
        <hr>
        {% crispy updateprofile_form %}
        <hr>
      </div>
      <div class="col-sm-4">
        <a href="{{profile.image_url}}" target="_blank">
          <img src="{{profile.thumb_url}}" class="img-fluid" alt="Responsive image">
        </a>
        {% crispy profilepicture_form %}
      </div>
      <div class="row pl-3">
        <div class="col">
          <input class="btn btn-secondary mt-2 p-1" type="submit" value="change">
        </div>
      </div>
    </div>
  </form>
</div>


</div>

{% endblock %}

users/templates/users/signup.html
{% extends "page/base_generic.html" %}

{% block content %}
<div class="containter p-3">
  <h2>Sign up</h2>

  <!-- <form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form> -->
  <form method="post">
    {% csrf_token %}
    <table>
      <!-- {{ signup_formset.management_form }} -->
      {{ signup_form.as_table }}
    </table>

    <!-- <h3>weitere Angaben:</h3> -->
    <!-- <table>
      {{ profile_formset.management_form }}
      {{ profile_formset.as_p }}
    </table> -->
    {{error}}
    <button class="btn btn-primary" type="submit">Sign up</button>
  </form>
</div>
{% endblock %}

users/templates/users/thanks.html
{% extends "page/base_generic.html" %}

{% block content %}
  <p>
    Registration completed! Thank you 
  </p>
  <a href="{% url 'users:login'%}">Click here to login.</a>
{% endblock %}